name: Build with Maven

on: [push]

jobs:
  build:
    strategy:
      matrix:
        java: ['8']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
          
      - name: Build with Maven
        run: mvn clean package

      - uses: actions/upload-artifact@master
        with:
          name: CloudNet-Transformer
          path: transformer-loader/target/CloudNetTransformer*
